#### 异步编程
```

* fs文件操作
* 数据库操作
* ajax
* 定时器
```

###### 使用promise的好处
    指定回调函数方式更灵活

        旧:启动异步任务之前指定

        新(promise)：启动异步任务--返回promise对象--给promise对象绑定回调函数

    支持链式调用 解决回调地狱

        回调地狱：一个异步任务里面嵌套着回调函数
            不便于阅读
            不便于解决异常处理

###### promise的使用
```
    Promise接收函数类型的参数   
        resolve:解决
        reject:拒绝

    //创建一个promise实例
    const p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            if(条件){
                
                resolve(成功的结果);//并且将promise对象的状态设置为成功
            }else{
               
                reject(失败的结果);//并且将promise对象的状态设置为
         失败
            }
        },1000)
    })  
    调用then方法
    p.then((value)=>{
        成功的回调 
    },(reson)=>{
         失败的回调
         
    }) 
```       
###### util.promisify(original)
```
    传入一个常见错误优先的回调函数
    const util = require('util');//引入util模块
    const fs = require('fs');//引入fs模块
    //返回一个promise对象
    let mineReadFile = util.promisify(fs.readFile);

    mineReadFile('路径').then(value=>{
        // 成功的回调
        },reason=>{
        // 失败的回调
    })
 ```   
###### Promise对象中的状态
```
    pending--未决定的(初始化)
    resolved(fullfilled)---成功的
    rejected--失败的

    只能有以下两种状态
    pending--->resolved
    pending--->rejected
    并且一个promise对象只能改变一次,无论成功失败 都会有一个结果数据
```
###### Promise对象的值
```
    保存异步任务的[成功/失败]结果
    resolve
    reject
```
###### Promise的流程
```
1.通过new关键字创建promise对象实例(此时状态为pending)
2.执行异步任务
    成功了,执行resolve()--->修改promise对象的状态为resolved--->通过then方法调用resolved()的回调
    失败了,执行reject()---->修改promise对象的状态为rejected--->通过then方法调用rejected失败的回调
3.最后回调结束以后返回一个新的promise对象
```
###### Promise中的API
```
promise接收的参数是一个函数类型的参数
我们称这种参数为(执行器):(resolve,reject)=>{}
执行器在promise的内部是立即调用,异步操作在执行器中执行
    举例说明 执行器执行的是同步任务
    const p = new Promise((resolve,reject)=>{
        //同步调用
        resolve('11')
    });
    console.log('22')
    输出:11 22

Promise.prototype.then()方法:(onResolved,onRejected)=>{}
    onResolved函数:成功的回调函数(value)=>{}
    onRejected函数:失败的回调函数(reason)=>{}

Promise.prototype.catch()方法
    举例说明:catch()方法只有在promise对象状态为rejected(失败)时调用
    const p = new Promise((resolve,reject)=>{
       reject('err')
    });
    p.catch(reason => {
       console.log(reason)
    });

Promise.resolve方法:(value) =>{}
    属于promise函数对象,不属于promsie实例对象
    value:成功的数据/promise对象
    作用:返回一个成功/失败的promise对象

    举例说明:
        let p1 = Promise.resolve(123)
        //如果传入的参数为非promise类型的对象,返回的都是状态为成功的promise对象
         console.log(p1)
         let p2 = Promise.resolve(new Promise((resolve,reject)=>{
            //如果传入的参数为promise类型的对象,返回的状态由传入的promise的状态决定
            resolve('ok')
         }));
         console.log(p2)//状态为成功 值为ok的promise对象

Promise.reject方法:(reason) =>{}
    属于promise函数对象,不属于promsie实例对象
    reject:失败的的数据/promise对象
    作用:返回一个失败的promise对象
       let p1 = Promise.reject(123)
        //如果传入的参数为非promise类型的对象,返回的都是状态为失败的promise对象
         console.log(p1)
         let p2 = Promise.reject(new Promise((resolve,reject)=>{
            //如果传入的参数为promise类型的对象,返回的都是失败的promise对象(即使传入成功的promise对象也返回失败)
            resolve('ok')
         }));
         console.log(p2)//状态为失败 值永远为传入的参数结果的promise对象
         
Promise.all()方法:(promises) =>{}
    promises:包含n个promise的数组
    返回一个新的promise,状态由数组中的promise状态决定(只有全部成功才成功,只要有一个失败就直接失败),而返回的结果值为数组,数组中为成功的promise的值组成。如果失败则返回的结果值为全为失败的promise数组
    promise.all()方法会发起并行的promise异步操作,等所有的异步操作全部结束后才执行下一步.then操作

    举例说明：
    //resolved
    let p1 = new Promise((resolve,reject)=>{
        resolve('ok');
    })
    let p2 = Promise.resolve('okok');
    let p3 = Promise.resolve('okokok');
    const result = Promise.all([p1,p2,p3]);
    console.log(result);//返回一个状态为成功的 值为['ok','okok','okokok']的promise对象

    //reject
    let p1 = new Promise((resolve,reject)=>{
        resolve('ok');
    })
    let p2 = Promise.reject('error');
    let p3 = Promise.resolve('okokok');
    const result = Promise.all([p1,p2,p3]);
    console.log(result);//返回一个状态为失败的 值为['error']的promise对象

Promise.race()方法,(promises) =>{}
promises:包含n个的promise数组
返回一个新的promise,第一个(不一定是数组中的第一个,是数组中最快读取的那一个)完成的promise的结果状态就是最终的结果状态

    举例说明:
    let p1 = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve('ok');
        },1000)
        
    })
    let p2 = Promise.resolve('okok');
    let p3 = Promise.resolve('okokok');
    const result = Promise.race([p1,p2,p3]);
    console.log(result);//返回一个新的promise,状态由第一个执行的promise决定(也就是p2的状态resolve),值为p2的('okok');
```


###### 一个Promise对象使用多个then指定多个成功/失败的回调函数,都会调用吗
```
当promise状态改变时都会被调用
    let p1 = new Promise((resolve,reject)=>{
        resolve('ok');
    })
    //指定回调1
    p.then(value =>{
        console.log(value);
    });
    //指定回调2
    p.then(value =>{
        console.log(value);
    });
//如果不执行resolve('ok'),那么Promise的状态始终为pending(状态没有改变)
//不会调用then里面的回调
```

###### 改变Promise状态和then方法中指定的回调函数,谁先执行
```
1.两者都可能先执行
    如果当前promise中执行器执行的为同步任务 则是先改变promise状态,然后在执行then方法中指定的回调函数
    举例说明：
        let p = new Promise((resolve,reject)=>{
            resolve('ok');
        });
        p.then((value)=>{
            console.log(value)
        },(reason)=>{
            console.log(reason)
        });
        //同步任务会先改变状态(pending--->resolve);
         再调用then()方法

//如何先改变状态再指定回调?
    1.在执行器中直接做一个同步任务 直接调用resolve()/reject();
    2.如果执行器中的任务为异步任务,我们可以延迟更长的时间调用then()---设置更长时间的定时器再去执行then()方法

    如果当前执行器中的任务是异步任务时,则先执行then方法中的回调函数,再改变promise的状态
    举例说明:
         let p = new Promise((resolve,reject)=>{
            setTimeout(()=>{
                 resolve('ok');
            },1000);
        });
        p.then((value)=>{
            console.log(value)
        },(reason)=>{
            console.log(reason)
        });
        //then方法中的回调函数先执行 改变状态后执行
        
//如何先指定回调再改变状态?
1.执行器里执行异步任务 
```
###### Promise.then()返回新的Promise结果由什么决定
```
简单来说是由当前执行的回调函数决定
    举例说明:
    let p = new Promise((resolve,reject)=>{
        resolve('ok');
    })
    //执行then方法
    p.then(value=>{
        console.log(value);//返回一个成功的promise 值为value

        //抛出错误
        throw '出现错误';//返回一个失败的promise 值为'出现错误'

        //返回一个非promise对象的结果
        return 123;//返回一个成功的promise 值为123;

        //返回的结果是一个promise对象,则由这个promise的状态决定
        return new Promise((resolve,reject)=>{
            resolve('success');//返回一个失败的promise对象
            reject('error');//返回一个失败的promise
        })

    },reason=>{
        console.log(reason)
    });
```
###### promise 如何串联多个操作
```    
then()方法后面可以返回一个promise对象 可以在then()方法中继续写promise
举例说明:
    let p =new Promise((resolve,reject)=>{
    setTimeout(()=>{
        resolve('ok');
    },1000)
});
p.then(value=>{
    return new Promise((resolve,reject)=>{
        resolve('okok')
    }).then(value =>{
        console.log(value)//okok
    }).then(value=>{
        console.log(value)//undefined
    })
    为什么是undefined???
},reason=>{});
```
###### Promise异常穿透
```
1.当使用Promise的then链式调用的时候,可以在最后指定失败的回调。
2.在前面任何操作出现了异常,都会传到最后的失败回调中处理
举例说明
(1)
    let p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve('ok');
        },1000)
    });
    p.then(value =>{
        console.log(1,value)
        return new Promise((resolve,reject)=>{
            resolve('okok')
        })
    }).then(value =>{
        console.log(2,value);
    }).then(value =>{
        console.log(3,value);
    }).catch(reason=>{
        console.warn(reason)
    })

    //全是成功的不出现异常则在一秒之后打印
    1 ok
    2 okok
    3 undefined(value的值为undefined undefined不属于promise);
(2)
    let p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            reject('error')
        },1000)
    });
    p.then(value =>{
        console.log(1,value)
        return new Promise((resolve,reject)=>{
            resolve('okok')
        })
    }).then(value =>{
        console.log(2,value);
    }).then(value =>{
        console.log(3,value);
    }).catch(reason=>{
        console.warn(reason)
    })
//由于promise中的状态变为reject 不再调用then()方法,但由于异常穿透 将由最后的catch()方法捕获
   输出:error      
(3)
    let p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve('ok')
        },1000)
    });
    p.then(value =>{
        console.log(1,value)
        return new Promise((resolve,reject)=>{
            resolve('okok')
        })
    }).then(value =>{
        throw 'errorerror'
    }).then(value =>{
        console.log(3,value);
    }).catch(reason=>{
        console.warn(reason)
    });
    //promise中的状态为resolve 一直链式调用then()方法,在调用then的途中遇到异常,由于异常穿透 将直接跳到最后被catch()方法捕获
    输出:
        1 ok
        errorerror
```
###### 如何中断Promise调用链
```
(唯一的方法)返回一个promise对象状态为pending
举例说明:
let p = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve('ok')
        },1000)
    });
    p.then(value =>{
        console.log(1,value)
        return new Promise(()=>{})
    }).then(value =>{
        console.log(2,value);
    });
    //返回的promise状态为pending 不再调用后面的then()方法 
    //输出：1 ok  
```
###### await表达式
```
.then链式调用的优点:解决了回调地狱的问题
.then链式调用的缺点:代码冗余,阅读性差,不易理解
使用async/await简化promise异步操作

1.await右侧表达式一般为promise对象,也可以为其他值
2.如果表达式为promise对象,await返回的是promise成功的值
    举例说明
    async function main(){
        let p = new Promise((resolve,reject)=>{
            resolve('ok')
        })
        let res = await p;
    }
    main()
3.如果表达式是其他值,直接将此值作为awit的返回值
     举例说明
    async function main(){
        let res = await 123;
        console.log(res);
    }
    main()
4.await必须写在async函数中,async函数中不必有await.
5.如果await的promise失败了,就会抛出异常,需要通过try...catch捕获处理
    举例说明
    async function main(){
        let p = new Promise((resolve,reject)=>{
            reject('error')
        });
        try{
            let res = await p;
        }catch(e){
            console.log(e)
        }
    }
    main()
6.在async方法中,第一个await之前的代码会同步执行,await之后的代码会异步执行
举例说明:
    console.log('A')
    async function getFile(){
        console.log('B')
        const r1 = await 读取文件1
        const r2 = await 读取文件2
        console.log(r1,r2)
        console.log('D')
    }
    getFile()
    console.log('C')
    输出结果 A,B,C,r1,r2,D(第一个await之前的代码会同步执行,后面的都是异步)
